on:
  push:
    branches:
      - main
      - dev
    paths:
      - "**/*.c"
      - "**/*.h"
      - .github/workflows/ci.yml
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up dependencies
        run: |
          sudo apt-get update
          # Purge mandb to speed up installation
          sudo apt-get purge -y man-db
          sudo apt-get install -y build-essential clang make pkg-config \
            xorg-dev xvfb xauth \
            libx11-dev libxext-dev libxrandr-dev libxrender-dev libxfixes-dev libxinerama-dev libxi-dev \
            libbsd-dev golang-go

      - name: Build project
        run: make all

      - name: Run tests
        run: make run_tests

      - name: Prepare for benchmark
        run: |
          make make_perf_maps

      - name: Run benchmark
        run: make re run_bench MODE=release FSAN=false
